"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollectionsROICalculator = CollectionsROICalculator;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const input_1 = require("@/components/ui/input");
function CollectionsROICalculator() {
    const [hours, setHours] = (0, react_1.useState)('5');
    const [rate, setRate] = (0, react_1.useState)('100');
    const [recoveryRate, setRecoveryRate] = (0, react_1.useState)('90');
    return ((0, jsx_runtime_1.jsxs)("div", { className: "p-6 sm:p-8 rounded-2xl border border-white/10 bg-zinc-900/50 backdrop-blur-sm", children: [(0, jsx_runtime_1.jsxs)("div", { className: "grid gap-4 sm:grid-cols-3", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-zinc-300 mb-1", children: "Hours/Month Chasing" }), (0, jsx_runtime_1.jsx)(input_1.Input, { type: "number", value: hours, onChange: e => setHours(e.target.value) })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-zinc-300 mb-1", children: "Your Hourly Rate ($)" }), (0, jsx_runtime_1.jsx)(input_1.Input, { type: "number", value: rate, onChange: e => setRate(e.target.value) })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-sm font-medium text-zinc-300 mb-1", children: "Current Recovery %" }), (0, jsx_runtime_1.jsx)(input_1.Input, { type: "number", value: recoveryRate, onChange: e => setRecoveryRate(e.target.value) })] })] }), hours && rate ? ((0, jsx_runtime_1.jsxs)("div", { className: "mt-8 p-6 rounded-xl border border-white/10 bg-white/[0.02]", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-zinc-100 mb-4", children: "Your Collections ROI:" }), (0, jsx_runtime_1.jsxs)("div", { className: "grid gap-4 sm:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("div", { className: "p-4 rounded-lg bg-zinc-800/50 border border-white/10 text-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "text-2xl font-bold text-zinc-200", children: ["$", (parseFloat(hours) * parseFloat(rate) * 12).toLocaleString()] }), (0, jsx_runtime_1.jsx)("div", { className: "text-xs text-zinc-400 mt-1", children: "Annual Cost of Manual Follow-ups" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-4 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "text-2xl font-bold text-emerald-400", children: ["$", ((parseFloat(hours) * parseFloat(rate) * 12) - (29 * 12)).toLocaleString()] }), (0, jsx_runtime_1.jsx)("div", { className: "text-xs text-emerald-300/70 mt-1", children: "Annual Savings with Duely ($29/mo)" })] })] })] })) : null] }));
}
