"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = NewCustomerLoading;
const jsx_runtime_1 = require("react/jsx-runtime");
const container_1 = require("@/components/site/container");
function Skeleton({ className = "" }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: `animate-pulse rounded-xl border border-white/10 bg-white/[0.04] ${className}` }));
}
function NewCustomerLoading() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex min-h-screen flex-col", children: [(0, jsx_runtime_1.jsx)("div", { className: "sticky top-0 z-20 border-b border-border bg-background/80 backdrop-blur-xl", children: (0, jsx_runtime_1.jsxs)(container_1.Container, { className: "flex h-16 items-center justify-between", children: [(0, jsx_runtime_1.jsx)(Skeleton, { className: "h-8 w-28" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-6 w-24" })] }) }), (0, jsx_runtime_1.jsx)("main", { id: "main-content", className: "flex-1", children: (0, jsx_runtime_1.jsx)(container_1.Container, { className: "py-8 sm:py-10", children: (0, jsx_runtime_1.jsxs)("div", { className: "mx-auto grid max-w-5xl gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", children: [(0, jsx_runtime_1.jsx)(Skeleton, { className: "h-12 w-56" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-5 w-full max-w-md" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-5 w-2/3 max-w-sm" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-2xl border border-border bg-white/[0.035] p-6", children: [(0, jsx_runtime_1.jsx)(Skeleton, { className: "h-7 w-44 mb-2" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-4 w-64 mb-6" }), (0, jsx_runtime_1.jsxs)("div", { className: "grid gap-5 sm:grid-cols-2", children: [(0, jsx_runtime_1.jsx)(Skeleton, { className: "h-16" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-16" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-16 sm:col-span-2" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-16 sm:col-span-2" })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)(Skeleton, { className: "h-32" }), (0, jsx_runtime_1.jsx)(Skeleton, { className: "h-44" })] })] }) }) })] }));
}
